apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbour-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbour-k8s
  template:
    metadata:
      labels:
        app: harbour-k8s
    spec:
      containers:
      - name: harbour-k8s
        image: kennethruan/harbour-nextjs
        ports:
        - containerPort: 3000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: nextjs-secret
              key: OPENAI_API_KEY
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nextjs-secret
              key: GOOGLE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: harbour-k8s
spec:
  type: NodePort
  selector:
    app: harbour-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
